server {
  # 1. Nginx escucha en el puerto 80 dentro del contenedor (coincide con el EXPOSE del Dockerfile)
  listen 80;

  # 2. La carpeta donde están los ficheros que copiamos en el Dockerfile (paso 7)
  root /usr/share/nginx/html;

  # 3. Si piden la raíz del sitio, sirve index.html
  index index.html;

  # 4. Regla clave para que funcione el Router de Angular
  location / {
    try_files $uri $uri/ /index.html;
  }
}
